---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap-case
  namespace: troubleshooting
data:
  nginx.cnf: |
    user  nginx;
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        access_log  /var/log/nginx/access.log  main;
        sendfile        on;
        keepalive_timeout  65;
        server {
            listen       80;
            server_name  localhost;
            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
            }
            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /usr/share/nginx/html;
            }
        }
    }
  mime.types: |
    types {
        text/html                                        html htm shtml;
        text/css                                         css;
        text/xml                                         xml;
        video/x-msvideo                                  avi;
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-configmap-case
  namespace: troubleshooting
  labels:
    app: nginx-configmap-case
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-configmap-case
  template:
    metadata:
      labels:
        app: nginx-configmap-case
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        volumeMounts:
         - name: config
           mountPath: /etc/nginx/
      volumes:
        - name: config
          configMap:
            name: nginx-confgmap-case
