---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nginx
  name: my-test-pvc
  namespace: troubleshooting
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeMode: Block
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pvc-case
  namespace: troubleshooting
  labels:
    app: nginx-pvc-case
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-pvc-case
  template:
    metadata:
      labels:
        app: nginx-pvc-case
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        volumeMounts:
         - name: mypvc
           mountPath: /var/lib/www/html
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: my-test-pvc
            readOnly: false
