---
apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  containers:
  - image: docker.io/library/wordpress:latest
    name: frontend
    args:
    - apache2-foreground
    ports:
    - containerPort: 80
      hostPort: 8080
  dnsPolicy: Default

