---
apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  containers:
  - image: docker.io/library/wordpress:latest
    name: frontend
    args:
    - apache2-foreground
    ports:
    - containerPort: 80
      hostPort: 8080
  # - name: mariadb
  #   image: docker.io/library/mariadb:10.6.4-focal
  #   command:
  #      - mysqld
  #      - --default-authentication-plugin=mysql_native_password
  #   ports:
  #   - containerPort: 33060
  #     hostPort: 33060
  #     protocol: TCP
  #   - containerPort: 3306
  #     hostPort: 3306
  #     protocol: TCP
  #   securityContext:
  #     runAsUser: 999
  #     runAsGroup: 999
  #   env:
  #   - name: MYSQL_ROOT_PASSWORD
  #     value: somewordpress
  #   - name: MYSQL_DATABASE
  #     value: wordpress
  #   - name: MYSQL_USER
  #     value: wordpress
  #   - name: MYSQL_PASSWORD
  #     value: wordpress
  dnsPolicy: Default

